spring.application.name=NarangNorang

# data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/narangnorang
spring.datasource.username=ureca
spring.datasource.password=ureca